### ISSUE TITLE
Is hypertag a regular language?

### ISSUE THREAD

**Issue by Nick-FV0523** [mwojnars/hypertag#2]
Created this a little early by accident, so I'm editing it now:

Python is not a regular language: https://stackoverflow.com/questions/6718202/what-is-a-regular-language#comment116921334_6718286

But is hypertag? I'm not much of a computer scientist.

If hypertag is not a regular language, then it would be impractical to parse with regular expressions, correct?

**Comment by mwojnars** [comment]
Not regular.
